title: Just the Cards
max_card_preview_length: 100

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: ['_site', ...]
